### ISSUE TITLE
Reconnect to DB if connection is failed

### ISSUE THREAD

**Issue by reindeer** [shootnix/activerecord-simple#106]
If time between two requests to DB is greater than timeout connection is down.
I've added workaround with sub{} in #75 pull request
Now you have added the code:
```
$self->db_connect unless $self->{dbh} && $self->{dbh}->ping;
```
There is an error during `$self->{dbh}->ping` call if `$self->{dbh}` is a sub {}
But seems your changes are made to reconnect to DB right?
If so 
```
return ref $self->{dbh} eq 'CODE' ? $self->{dbh}->() : $self->{dbh};
```
should be replaced to 
```
return $self->{dbh};
```

**Comment by shootnix** [comment]
Why don't you send a pull-request? ;-)

**Comment by reindeer** [comment]
Because I'm not sure if I'm right =)

**Comment by shootnix** [comment]
I'm sure you're right.
