### ISSUE TITLE
Is any way to add computed field to select condition?

### ISSUE THREAD

**Issue by reindeer** [shootnix/activerecord-simple#84]
For example I need computed field like following:
`if(finished,3,if(date>date(now()),2,if(date<date(now()), 1, 0))) as state`
Can I add this field to select?

**Comment by shootnix** [comment]
Hi, this is a quite interesting feature, but it needs to be done. =) Please, create an issue, if you still need this thing.

**Comment by reindeer** [comment]
Hi
Sorry I didn't understand your comment. This issue has been create, right? What do you mean?
Actually I don't have any ideas how to implement this feature.

I need: `select name, date(updated) as release_date from records`
```->find()->some_method_for_custom_column('date(updated) as release_date')```
bad solution because we don't know which part of string contains column name (so where should we add `"$table_name".""`)

**Comment by shootnix** [comment]
There is no need to create a super-duper new method for this feature I think. We already have "columns" method where we can describe every column we need. This method needs to be extended. And few another I guess.

**Comment by reindeer** [comment]
I guess that calculated fields are not part of the Model but query-specific feature.
I mean if one request requires complicated calculations other ones do not need pay extended time

**Comment by shootnix** [comment]
Now, you can use simple "mixins" method to add some code in the select area. Mixin has its own name so you can get access to it.

In your class:

`__PACKAGE__->mixins(calc => sub { return 'SUM(id) AS calc'});`

In your code:

`Model->find({some => 'criteria'})->fields('some', 'calc')->fetch;`

**Comment by reindeer** [comment]
Nice solution

Two notice:
1. `__PACKAGE__->mixins(calc => sub { return 'SUM(id) AS calc'});` mixin name and `AS` name should be the same, right? So `__PACKAGE__->mixins(calc => sub { return 'SUM(id)'});` should be enough
2. `->to_hash` doesn't return this field

**Comment by shootnix** [comment]
I see one more approach needed to solve this issue. =) Thanks.
