### ISSUE TITLE
asc/desc for every column

### ISSUE THREAD

**Issue by reindeer** [shootnix/activerecord-simple#86]
`asc`/`desc` can be called for every column, not for all request
Current API allows to set the order for the whole request but order for column isn't worked.

There are two variants I can suggest:
1 `Model->odrer_by('name', ['age' => 'desc'])->fetch`
2 `Model->odrer_by('name', {column => 'age', direction => 'desc'])->fetch`

Patch should be following:
1.
```
--- ActiveRecord/Simple/Find.pm.orig    2017-08-03 18:04:50.266076872 +0300
+++ ActiveRecord/Simple/Find.pm       2017-08-03 18:01:43.854075868 +0300
@@ -329,7 +329,7 @@

     if (defined $self->{prep_order_by}) {
         $self->{SQL} .= ' ORDER BY ';
-                $self->{SQL} .= join q/, /, map { q/"/.$_.q/"/ } @{ $self->{prep_order_by} };
+                $self->{SQL} .= join q/, /, map { ref $_ ? qq/"$_->[0]" $_->[1]/: qq/"$_"/ } @{ $self->{prep_order_by} };

     }

     $self->{SQL} .= ' DESC ' if defined $self->{prep_desc};
```

2.
```
--- ActiveRecord/Simple/Find.pm.orig    2017-08-03 18:04:50.266076872 +0300
+++ ActiveRecord/Simple/Find.pm       2017-08-03 18:01:43.854075868 +0300
@@ -329,7 +329,7 @@

     if (defined $self->{prep_order_by}) {
         $self->{SQL} .= ' ORDER BY ';
-                $self->{SQL} .= join q/, /, map { q/"/.$_.q/"/ } @{ $self->{prep_order_by} };
+                $self->{SQL} .= join q/, /, map { ref $_ ? qq/"$_->{column}" $_->{direction}/: qq/"$_"/ } @{ $self->{prep_order_by} };

     }

     $self->{SQL} .= ' DESC ' if defined $self->{prep_desc};
```

I don't know which variant is prefferable
What do you think about it?

**Comment by shootnix** [comment]
I like the idea, but API doesn't look beautiful to me. It would be great if will keep simple semantic for this:

`order_by('name)->desc->order_by('age')->asc`

What about this?

**Comment by reindeer** [comment]
well, what is expected behavious in that case?
```order_by('name', 'age')->desc```?

**Comment by shootnix** [comment]
I think it has to be mapped in this way:

order_by('name')->desc->order_by('age', 'gender')->asc --> ORDER BY 'name' DESC, 'age', 'gender' ASC;

i.e. as much transparent as possible. In this case, I believe asc & disc functions are simply syntactic sugar or may be just an 'Add new word' function' =)

**Comment by reindeer** [comment]
Well, make sense.
But now asc/desc is only variable `$self->{prep_desc}` so a lot of things should be implement to make this API

**Comment by shootnix** [comment]
yep ;-)
