### ISSUE TITLE
Change API for count() method

### ISSUE THREAD

**Issue by reindeer** [shootnix/activerecord-simple#92]
Currently `count()` method is a static. So we cannot add some conditions. For example I would like to add `group_by()` method and use it with count but I can't
So what do you think if `count()` method returns `ActiveRecord::Simple::Find` object? In that case we can add limits, offsets, etc. but API should be changed. I mean now `Model->count` isn't allowed but `Model->count->fetch->count` is required

**Comment by shootnix** [comment]
`Model->count->fetch->count`
Looks terrible =)

**Comment by reindeer** [comment]
Yes!

**Comment by reindeer** [comment]
Actually, fetched object for `Model->count->group_by('age')->fetch` is following:
```
bless( {
  "COUNT(*)" => 2,
  "isin_database" => 1,
  "age" => 18
}, 'Model' )
```
So some alias for `COUNT(*)` is needed

**Comment by reindeer** [comment]
Also mixin isn't allowed here because `$pk` is added to `@fields`
```if ($self->{class}->can('_get_primary_key')) {
        my $pk = $self->{class}->_get_primary_key;
        push @fields, $pk if ! grep { $_ eq $pk } @fields;
    }```

**Comment by reindeer** [comment]
Ruby version
```
Person.all.group(:name).count
(1.2ms)  SELECT COUNT(*) AS count_all, name AS name FROM "people" GROUP BY "people"."name"
=> {"Dan"=>3, "Dave"=>2, "Vic"=>1} 
```
Can we do the same?
`Model->find->group_by(age)->count`

**Comment by shootnix** [comment]
Done, but the old API has to be alive for a while, I guess.

**Comment by reindeer** [comment]
Why?
`new_count()` works as expected. So we don't need for the old `count()` method

**Comment by shootnix** [comment]
I think I use this method in some places =)

**Comment by reindeer** [comment]
Am I right and you need to use `Model->count({some => "criteria"})`? `new_count()` allows to do that. If you use `Model->count()` you get a correct number.

**Comment by reindeer** [comment]
Just another realisation of the method but API has backward compatibility

**Comment by shootnix** [comment]
Yep. Let's make "new_count" just private method and "count" will be changed in the future. Right now we can use both: Model->count & Model->find->count. In the 1.0 I'll kill the old version, I promise.

**Comment by reindeer** [comment]
I don't understand why do you need old count() if new_count provides both `Model->count` & `Model->find->count`.
But as you wish =)

**Comment by reindeer** [comment]
Your changes breaks `Model->find->group_by('field')->count`: returns only first value. Why did you do that?

**Comment by shootnix** [comment]
Sorry about that. It wasn't obvious to me because you don't write tests. Could you please create path in develop with tests?

**Comment by reindeer** [comment]
Sorry, I don't know how to write tests.

**Comment by shootnix** [comment]
ok

**Comment by reindeer** [comment]
My previous patch made following:
* `Model->count($criteria)` => static method, returns a number like old `count()`
* `Model->find($criteria)->count` => returns a number, works like previous but for the object
* `Model->find($criteria)->group_by('field')->count` => returns `[{field => "field", count => "count"},{...}]` where every hash contains all `GROUP BY` fields

I don't have any idea how to test it

**Comment by shootnix** [comment]
Please, look at tests in "t" directory of the project. You can use existing file 07-find.t or even create yours, it doesn't matter.

**Comment by reindeer** [comment]
Just re-create Pull Request with tests, right?

**Comment by shootnix** [comment]
Yes, please, in "develop" branch.

**Comment by shootnix** [comment]
Good job, anyway. =)
